package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1



/**
 * TbAcceso generated by hbm2java
 */
public class TbAcceso  implements java.io.Serializable {


     private Integer id;
     private TbUsuarios tbUsuarios;
     private String login;
     private String pass;

    public TbAcceso() {
    }

    public TbAcceso(TbUsuarios tbUsuarios, String login, String pass) {
       this.tbUsuarios = tbUsuarios;
       this.login = login;
       this.pass = pass;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


