package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCanton generated by hbm2java
 */
public class TbCanton  implements java.io.Serializable {


     private TbCantonId id;
     private TbProvincia tbProvincia;
     private String nombre;
     private Set tbParroquias = new HashSet(0);

    public TbCanton() {
    }

	
    public TbCanton(TbCantonId id, TbProvincia tbProvincia) {
        this.id = id;
        this.tbProvincia = tbProvincia;
    }
    public TbCanton(TbCantonId id, TbProvincia tbProvincia, String nombre, Set tbParroquias) {
       this.id = id;
       this.tbProvincia = tbProvincia;
       this.nombre = nombre;
       this.tbParroquias = tbParroquias;
    }
   
    public TbCantonId getId() {
        return this.id;
    }
    
    public void setId(TbCantonId id) {
        this.id = id;
    }
    public TbProvincia getTbProvincia() {
        return this.tbProvincia;
    }
    
    public void setTbProvincia(TbProvincia tbProvincia) {
        this.tbProvincia = tbProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTbParroquias() {
        return this.tbParroquias;
    }
    
    public void setTbParroquias(Set tbParroquias) {
        this.tbParroquias = tbParroquias;
    }




}


