package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCanton generated by hbm2java
 */
public class TbCanton  implements java.io.Serializable {


     private String idCanton;
     private TbProvincia tbProvincia;
     private String nombre;
     private Set tbParroquias = new HashSet(0);

    public TbCanton() {
    }

	
    public TbCanton(String idCanton, TbProvincia tbProvincia) {
        this.idCanton = idCanton;
        this.tbProvincia = tbProvincia;
    }
    public TbCanton(String idCanton, TbProvincia tbProvincia, String nombre, Set tbParroquias) {
       this.idCanton = idCanton;
       this.tbProvincia = tbProvincia;
       this.nombre = nombre;
       this.tbParroquias = tbParroquias;
    }
   
    public String getIdCanton() {
        return this.idCanton;
    }
    
    public void setIdCanton(String idCanton) {
        this.idCanton = idCanton;
    }
    public TbProvincia getTbProvincia() {
        return this.tbProvincia;
    }
    
    public void setTbProvincia(TbProvincia tbProvincia) {
        this.tbProvincia = tbProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTbParroquias() {
        return this.tbParroquias;
    }
    
    public void setTbParroquias(Set tbParroquias) {
        this.tbParroquias = tbParroquias;
    }




}


