package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCanton generated by hbm2java
 */
public class TbCanton  implements java.io.Serializable {


     private String id;
     private TbProvincia tbProvincia;
     private String nombre;
     private Set tbParroquias = new HashSet(0);

    public TbCanton() {
    }

	
    public TbCanton(String id, TbProvincia tbProvincia) {
        this.id = id;
        this.tbProvincia = tbProvincia;
    }
    public TbCanton(String id, TbProvincia tbProvincia, String nombre, Set tbParroquias) {
       this.id = id;
       this.tbProvincia = tbProvincia;
       this.nombre = nombre;
       this.tbParroquias = tbParroquias;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TbProvincia getTbProvincia() {
        return this.tbProvincia;
    }
    
    public void setTbProvincia(TbProvincia tbProvincia) {
        this.tbProvincia = tbProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTbParroquias() {
        return this.tbParroquias;
    }
    
    public void setTbParroquias(Set tbParroquias) {
        this.tbParroquias = tbParroquias;
    }




}


