package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1



/**
 * TbCantonId generated by hbm2java
 */
public class TbCantonId  implements java.io.Serializable {


     private String id;
     private String tbProvinciaId;

    public TbCantonId() {
    }

    public TbCantonId(String id, String tbProvinciaId) {
       this.id = id;
       this.tbProvinciaId = tbProvinciaId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTbProvinciaId() {
        return this.tbProvinciaId;
    }
    
    public void setTbProvinciaId(String tbProvinciaId) {
        this.tbProvinciaId = tbProvinciaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbCantonId) ) return false;
		 TbCantonId castOther = ( TbCantonId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getTbProvinciaId()==castOther.getTbProvinciaId()) || ( this.getTbProvinciaId()!=null && castOther.getTbProvinciaId()!=null && this.getTbProvinciaId().equals(castOther.getTbProvinciaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getTbProvinciaId() == null ? 0 : this.getTbProvinciaId().hashCode() );
         return result;
   }   


}


