package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TbDetallepedidos generated by hbm2java
 */
public class TbDetallepedidos  implements java.io.Serializable {


     private Integer id;
     private TbPedidos tbPedidos;
     private TbProducto tbProducto;
     private Integer cantidadProducto;
     private BigDecimal preciouni;
     private BigDecimal preciodetalle;
     private Boolean estado;

    public TbDetallepedidos() {
    }

	
    public TbDetallepedidos(TbPedidos tbPedidos, TbProducto tbProducto) {
        this.tbPedidos = tbPedidos;
        this.tbProducto = tbProducto;
    }
    public TbDetallepedidos(TbPedidos tbPedidos, TbProducto tbProducto, Integer cantidadProducto, BigDecimal preciouni, BigDecimal preciodetalle, Boolean estado) {
       this.tbPedidos = tbPedidos;
       this.tbProducto = tbProducto;
       this.cantidadProducto = cantidadProducto;
       this.preciouni = preciouni;
       this.preciodetalle = preciodetalle;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbPedidos getTbPedidos() {
        return this.tbPedidos;
    }
    
    public void setTbPedidos(TbPedidos tbPedidos) {
        this.tbPedidos = tbPedidos;
    }
    public TbProducto getTbProducto() {
        return this.tbProducto;
    }
    
    public void setTbProducto(TbProducto tbProducto) {
        this.tbProducto = tbProducto;
    }
    public Integer getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(Integer cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public BigDecimal getPreciouni() {
        return this.preciouni;
    }
    
    public void setPreciouni(BigDecimal preciouni) {
        this.preciouni = preciouni;
    }
    public BigDecimal getPreciodetalle() {
        return this.preciodetalle;
    }
    
    public void setPreciodetalle(BigDecimal preciodetalle) {
        this.preciodetalle = preciodetalle;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


