package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TbDetallefactura generated by hbm2java
 */
public class TbDetallefactura  implements java.io.Serializable {


     private Integer id;
     private TbFactura tbFactura;
     private TbProducto tbProducto;
     private BigDecimal precioDetalle;
     private String tbDetallefacturacol;
     private BigDecimal iva;
     private BigDecimal precioxund;

    public TbDetallefactura() {
    }

	
    public TbDetallefactura(TbFactura tbFactura, TbProducto tbProducto) {
        this.tbFactura = tbFactura;
        this.tbProducto = tbProducto;
    }
    public TbDetallefactura(TbFactura tbFactura, TbProducto tbProducto, BigDecimal precioDetalle, String tbDetallefacturacol, BigDecimal iva, BigDecimal precioxund) {
       this.tbFactura = tbFactura;
       this.tbProducto = tbProducto;
       this.precioDetalle = precioDetalle;
       this.tbDetallefacturacol = tbDetallefacturacol;
       this.iva = iva;
       this.precioxund = precioxund;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbFactura getTbFactura() {
        return this.tbFactura;
    }
    
    public void setTbFactura(TbFactura tbFactura) {
        this.tbFactura = tbFactura;
    }
    public TbProducto getTbProducto() {
        return this.tbProducto;
    }
    
    public void setTbProducto(TbProducto tbProducto) {
        this.tbProducto = tbProducto;
    }
    public BigDecimal getPrecioDetalle() {
        return this.precioDetalle;
    }
    
    public void setPrecioDetalle(BigDecimal precioDetalle) {
        this.precioDetalle = precioDetalle;
    }
    public String getTbDetallefacturacol() {
        return this.tbDetallefacturacol;
    }
    
    public void setTbDetallefacturacol(String tbDetallefacturacol) {
        this.tbDetallefacturacol = tbDetallefacturacol;
    }

    public BigDecimal getIva() {
        return iva;
    }

    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }

    public BigDecimal getPrecioxund() {
        return precioxund;
    }

    public void setPrecioxund(BigDecimal precioxund) {
        this.precioxund = precioxund;
    }
    



}


