package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TbDetallefactura generated by hbm2java
 */
public class TbDetallefactura  implements java.io.Serializable {


     private Integer id;
     private TbFactura tbFactura;
     private TbProducto tbProducto;
     private BigDecimal precioDetalle;
     private String tbDetallefacturacol;

    public TbDetallefactura() {
    }

	
    public TbDetallefactura(TbFactura tbFactura, TbProducto tbProducto) {
        this.tbFactura = tbFactura;
        this.tbProducto = tbProducto;
    }
    public TbDetallefactura(TbFactura tbFactura, TbProducto tbProducto, BigDecimal precioDetalle, String tbDetallefacturacol) {
       this.tbFactura = tbFactura;
       this.tbProducto = tbProducto;
       this.precioDetalle = precioDetalle;
       this.tbDetallefacturacol = tbDetallefacturacol;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbFactura getTbFactura() {
        return this.tbFactura;
    }
    
    public void setTbFactura(TbFactura tbFactura) {
        this.tbFactura = tbFactura;
    }
    public TbProducto getTbProducto() {
        return this.tbProducto;
    }
    
    public void setTbProducto(TbProducto tbProducto) {
        this.tbProducto = tbProducto;
    }
    public BigDecimal getPrecioDetalle() {
        return this.precioDetalle;
    }
    
    public void setPrecioDetalle(BigDecimal precioDetalle) {
        this.precioDetalle = precioDetalle;
    }
    public String getTbDetallefacturacol() {
        return this.tbDetallefacturacol;
    }
    
    public void setTbDetallefacturacol(String tbDetallefacturacol) {
        this.tbDetallefacturacol = tbDetallefacturacol;
    }




}


