package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1



/**
 * TbDetallePermiso generated by hbm2java
 */
public class TbDetallePermiso  implements java.io.Serializable {


     private Integer id;
     private TbPermiso tbPermiso;
     private TbUsuarios tbUsuarios;
     private Character estado;

    public TbDetallePermiso() {
    }

    public TbDetallePermiso(TbPermiso tbPermiso, TbUsuarios tbUsuarios, Character estado) {
       this.tbPermiso = tbPermiso;
       this.tbUsuarios = tbUsuarios;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbPermiso getTbPermiso() {
        return this.tbPermiso;
    }
    
    public void setTbPermiso(TbPermiso tbPermiso) {
        this.tbPermiso = tbPermiso;
    }
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


