package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbEmpresa generated by hbm2java
 */
public class TbEmpresa  implements java.io.Serializable {


     private Integer id;
     private TbParroquia tbParroquia;
     private TbTipoempresa tbTipoempresa;
     private String razonSocial;
     private String ruc;
     private String direccion;
     private Set tbUsuarioses = new HashSet(0);

    public TbEmpresa() {
    }

	
    public TbEmpresa(TbParroquia tbParroquia, TbTipoempresa tbTipoempresa) {
        this.tbParroquia = tbParroquia;
        this.tbTipoempresa = tbTipoempresa;
    }
    public TbEmpresa(TbParroquia tbParroquia, TbTipoempresa tbTipoempresa, String razonSocial, String ruc, String direccion, Set tbUsuarioses) {
       this.tbParroquia = tbParroquia;
       this.tbTipoempresa = tbTipoempresa;
       this.razonSocial = razonSocial;
       this.ruc = ruc;
       this.direccion = direccion;
       this.tbUsuarioses = tbUsuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbParroquia getTbParroquia() {
        return this.tbParroquia;
    }
    
    public void setTbParroquia(TbParroquia tbParroquia) {
        this.tbParroquia = tbParroquia;
    }
    public TbTipoempresa getTbTipoempresa() {
        return this.tbTipoempresa;
    }
    
    public void setTbTipoempresa(TbTipoempresa tbTipoempresa) {
        this.tbTipoempresa = tbTipoempresa;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTbUsuarioses() {
        return this.tbUsuarioses;
    }
    
    public void setTbUsuarioses(Set tbUsuarioses) {
        this.tbUsuarioses = tbUsuarioses;
    }




}


