package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TbInventario generated by hbm2java
 */
public class TbInventario  implements java.io.Serializable {


     private Integer id;
     private TbProducto tbProducto;
     private Integer stock;
     private Integer cantidadMinima;
     private BigDecimal precioStock;
     private Date fecharegistro;

    public TbInventario() {
    }

	
    public TbInventario(TbProducto tbProducto) {
        this.tbProducto = tbProducto;
    }
    public TbInventario(TbProducto tbProducto, Integer stock, Integer cantidadMinima, BigDecimal precioStock, Date fecharegistro) {
       this.tbProducto = tbProducto;
       this.stock = stock;
       this.cantidadMinima = cantidadMinima;
       this.precioStock = precioStock;
       this.fecharegistro = fecharegistro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbProducto getTbProducto() {
        return this.tbProducto;
    }
    
    public void setTbProducto(TbProducto tbProducto) {
        this.tbProducto = tbProducto;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Integer getCantidadMinima() {
        return this.cantidadMinima;
    }
    
    public void setCantidadMinima(Integer cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }
    public BigDecimal getPrecioStock() {
        return this.precioStock;
    }
    
    public void setPrecioStock(BigDecimal precioStock) {
        this.precioStock = precioStock;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


