package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1



/**
 * TbParroquiaId generated by hbm2java
 */
public class TbParroquiaId  implements java.io.Serializable {


     private String id;
     private String tbCantonId;
     private String tbCantonIdProvincia;

    public TbParroquiaId() {
    }

    public TbParroquiaId(String id, String tbCantonId, String tbCantonIdProvincia) {
       this.id = id;
       this.tbCantonId = tbCantonId;
       this.tbCantonIdProvincia = tbCantonIdProvincia;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTbCantonId() {
        return this.tbCantonId;
    }
    
    public void setTbCantonId(String tbCantonId) {
        this.tbCantonId = tbCantonId;
    }
    public String getTbCantonIdProvincia() {
        return this.tbCantonIdProvincia;
    }
    
    public void setTbCantonIdProvincia(String tbCantonIdProvincia) {
        this.tbCantonIdProvincia = tbCantonIdProvincia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbParroquiaId) ) return false;
		 TbParroquiaId castOther = ( TbParroquiaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getTbCantonId()==castOther.getTbCantonId()) || ( this.getTbCantonId()!=null && castOther.getTbCantonId()!=null && this.getTbCantonId().equals(castOther.getTbCantonId()) ) )
 && ( (this.getTbCantonIdProvincia()==castOther.getTbCantonIdProvincia()) || ( this.getTbCantonIdProvincia()!=null && castOther.getTbCantonIdProvincia()!=null && this.getTbCantonIdProvincia().equals(castOther.getTbCantonIdProvincia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getTbCantonId() == null ? 0 : this.getTbCantonId().hashCode() );
         result = 37 * result + ( getTbCantonIdProvincia() == null ? 0 : this.getTbCantonIdProvincia().hashCode() );
         return result;
   }   


}


