package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPais generated by hbm2java
 */
public class TbPais  implements java.io.Serializable {


     private String id;
     private String nombre;
     private String nacionalidad;
     private Set tbProvincias = new HashSet(0);

    public TbPais() {
    }

	
    public TbPais(String id) {
        this.id = id;
    }
    public TbPais(String id, String nombre, String nacionalidad, Set tbProvincias) {
       this.id = id;
       this.nombre = nombre;
       this.nacionalidad = nacionalidad;
       this.tbProvincias = tbProvincias;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Set getTbProvincias() {
        return this.tbProvincias;
    }
    
    public void setTbProvincias(Set tbProvincias) {
        this.tbProvincias = tbProvincias;
    }




}


