package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbParroquia generated by hbm2java
 */
public class TbParroquia  implements java.io.Serializable {


     private String id;
     private TbCanton tbCanton;
     private String nombre;
     private Set tbUsuarioses = new HashSet(0);
     private Set tbEmpresas = new HashSet(0);
     private Set tbPersonas = new HashSet(0);

    public TbParroquia() {
    }

	
    public TbParroquia(String id, TbCanton tbCanton) {
        this.id = id;
        this.tbCanton = tbCanton;
    }
    public TbParroquia(String id, TbCanton tbCanton, String nombre, Set tbUsuarioses, Set tbEmpresas, Set tbPersonas) {
       this.id = id;
       this.tbCanton = tbCanton;
       this.nombre = nombre;
       this.tbUsuarioses = tbUsuarioses;
       this.tbEmpresas = tbEmpresas;
       this.tbPersonas = tbPersonas;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TbCanton getTbCanton() {
        return this.tbCanton;
    }
    
    public void setTbCanton(TbCanton tbCanton) {
        this.tbCanton = tbCanton;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTbUsuarioses() {
        return this.tbUsuarioses;
    }
    
    public void setTbUsuarioses(Set tbUsuarioses) {
        this.tbUsuarioses = tbUsuarioses;
    }
    public Set getTbEmpresas() {
        return this.tbEmpresas;
    }
    
    public void setTbEmpresas(Set tbEmpresas) {
        this.tbEmpresas = tbEmpresas;
    }
    public Set getTbPersonas() {
        return this.tbPersonas;
    }
    
    public void setTbPersonas(Set tbPersonas) {
        this.tbPersonas = tbPersonas;
    }




}


