package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPermiso generated by hbm2java
 */
public class TbPermiso  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Integer padre;
     private String form;
     private Integer orden;
     private Character estado;
     private Set tbDetallePermisos = new HashSet(0);

    public TbPermiso() {
    }

    public TbPermiso(String descripcion, Integer padre, String form, Integer orden, Character estado, Set tbDetallePermisos) {
       this.descripcion = descripcion;
       this.padre = padre;
       this.form = form;
       this.orden = orden;
       this.estado = estado;
       this.tbDetallePermisos = tbDetallePermisos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPadre() {
        return this.padre;
    }
    
    public void setPadre(Integer padre) {
        this.padre = padre;
    }
    public String getForm() {
        return this.form;
    }
    
    public void setForm(String form) {
        this.form = form;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getTbDetallePermisos() {
        return this.tbDetallePermisos;
    }
    
    public void setTbDetallePermisos(Set tbDetallePermisos) {
        this.tbDetallePermisos = tbDetallePermisos;
    }




}


