package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPedidos generated by hbm2java
 */
public class TbPedidos  implements java.io.Serializable {


     private Integer id;
     private TbPersona tbPersona;
     private TbTipopago tbTipopago;
     private TbTipopedido tbTipopedido;
     private TbUsuarios tbUsuarios;
     private Date fechaPedido;
     private Date fechaEntrega;
     private Integer estado;
     private Set tbDetallepedidoses = new HashSet(0);

    public TbPedidos() {
    }

	
    public TbPedidos(TbPersona tbPersona, TbTipopago tbTipopago, TbTipopedido tbTipopedido, TbUsuarios tbUsuarios) {
        this.tbPersona = tbPersona;
        this.tbTipopago = tbTipopago;
        this.tbTipopedido = tbTipopedido;
        this.tbUsuarios = tbUsuarios;
    }
    public TbPedidos(TbPersona tbPersona, TbTipopago tbTipopago, TbTipopedido tbTipopedido, TbUsuarios tbUsuarios, Date fechaPedido, Date fechaEntrega, Integer estado, Set tbDetallepedidoses) {
       this.tbPersona = tbPersona;
       this.tbTipopago = tbTipopago;
       this.tbTipopedido = tbTipopedido;
       this.tbUsuarios = tbUsuarios;
       this.fechaPedido = fechaPedido;
       this.fechaEntrega = fechaEntrega;
       this.estado = estado;
       this.tbDetallepedidoses = tbDetallepedidoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbPersona getTbPersona() {
        return this.tbPersona;
    }
    
    public void setTbPersona(TbPersona tbPersona) {
        this.tbPersona = tbPersona;
    }
    public TbTipopago getTbTipopago() {
        return this.tbTipopago;
    }
    
    public void setTbTipopago(TbTipopago tbTipopago) {
        this.tbTipopago = tbTipopago;
    }
    public TbTipopedido getTbTipopedido() {
        return this.tbTipopedido;
    }
    
    public void setTbTipopedido(TbTipopedido tbTipopedido) {
        this.tbTipopedido = tbTipopedido;
    }
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getTbDetallepedidoses() {
        return this.tbDetallepedidoses;
    }
    
    public void setTbDetallepedidoses(Set tbDetallepedidoses) {
        this.tbDetallepedidoses = tbDetallepedidoses;
    }




}


