package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbPedidos generated by hbm2java
 */
public class TbPedidos  implements java.io.Serializable {


     private Integer id;
     private TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopedido;
     private TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopago;
     private TbPersona tbPersona;
     private TbUsuarios tbUsuarios;
     private Date fechaPedido;
     private Date fechaEntrega;
     private Integer estado;
     private Set tbDetallepedidoses = new HashSet(0);

    public TbPedidos() {
    }

	
    public TbPedidos(TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopedido, TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopago, TbPersona tbPersona, TbUsuarios tbUsuarios) {
        this.tbParametrodetalleByTbParametrodetalleTipopedido = tbParametrodetalleByTbParametrodetalleTipopedido;
        this.tbParametrodetalleByTbParametrodetalleTipopago = tbParametrodetalleByTbParametrodetalleTipopago;
        this.tbPersona = tbPersona;
        this.tbUsuarios = tbUsuarios;
    }
    public TbPedidos(TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopedido, TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopago, TbPersona tbPersona, TbUsuarios tbUsuarios, Date fechaPedido, Date fechaEntrega, Integer estado, Set tbDetallepedidoses) {
       this.tbParametrodetalleByTbParametrodetalleTipopedido = tbParametrodetalleByTbParametrodetalleTipopedido;
       this.tbParametrodetalleByTbParametrodetalleTipopago = tbParametrodetalleByTbParametrodetalleTipopago;
       this.tbPersona = tbPersona;
       this.tbUsuarios = tbUsuarios;
       this.fechaPedido = fechaPedido;
       this.fechaEntrega = fechaEntrega;
       this.estado = estado;
       this.tbDetallepedidoses = tbDetallepedidoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbParametrodetalle getTbParametrodetalleByTbParametrodetalleTipopedido() {
        return this.tbParametrodetalleByTbParametrodetalleTipopedido;
    }
    
    public void setTbParametrodetalleByTbParametrodetalleTipopedido(TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopedido) {
        this.tbParametrodetalleByTbParametrodetalleTipopedido = tbParametrodetalleByTbParametrodetalleTipopedido;
    }
    public TbParametrodetalle getTbParametrodetalleByTbParametrodetalleTipopago() {
        return this.tbParametrodetalleByTbParametrodetalleTipopago;
    }
    
    public void setTbParametrodetalleByTbParametrodetalleTipopago(TbParametrodetalle tbParametrodetalleByTbParametrodetalleTipopago) {
        this.tbParametrodetalleByTbParametrodetalleTipopago = tbParametrodetalleByTbParametrodetalleTipopago;
    }
    public TbPersona getTbPersona() {
        return this.tbPersona;
    }
    
    public void setTbPersona(TbPersona tbPersona) {
        this.tbPersona = tbPersona;
    }
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getTbDetallepedidoses() {
        return this.tbDetallepedidoses;
    }
    
    public void setTbDetallepedidoses(Set tbDetallepedidoses) {
        this.tbDetallepedidoses = tbDetallepedidoses;
    }




}


