package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipopersona generated by hbm2java
 */
public class TbTipopersona  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set tbPersonas = new HashSet(0);

    public TbTipopersona() {
    }

	
    public TbTipopersona(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TbTipopersona(String nombre, String descripcion, Set tbPersonas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tbPersonas = tbPersonas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbPersonas() {
        return this.tbPersonas;
    }
    
    public void setTbPersonas(Set tbPersonas) {
        this.tbPersonas = tbPersonas;
    }




}


