package Pojo;
// Generated 02-ago-2016 20:53:09 by Hibernate Tools 4.3.1



/**
 * TbTipoUsuario generated by hbm2java
 */
public class TbTipoUsuario  implements java.io.Serializable {


     private Integer id;
     private TbUsuarios tbUsuarios;
     private String descripcion;

    public TbTipoUsuario() {
    }

    public TbTipoUsuario(TbUsuarios tbUsuarios, String descripcion) {
       this.tbUsuarios = tbUsuarios;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TbUsuarios getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(TbUsuarios tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


