package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipounidadmedida generated by hbm2java
 */
public class TbTipounidadmedida  implements java.io.Serializable {


     private String idTipoUnidadmedida;
     private String nombre;
     private String descripcion;
     private Set tbProductos = new HashSet(0);

    public TbTipounidadmedida() {
    }

	
    public TbTipounidadmedida(String idTipoUnidadmedida, String nombre, String descripcion) {
        this.idTipoUnidadmedida = idTipoUnidadmedida;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TbTipounidadmedida(String idTipoUnidadmedida, String nombre, String descripcion, Set tbProductos) {
       this.idTipoUnidadmedida = idTipoUnidadmedida;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tbProductos = tbProductos;
    }
   
    public String getIdTipoUnidadmedida() {
        return this.idTipoUnidadmedida;
    }
    
    public void setIdTipoUnidadmedida(String idTipoUnidadmedida) {
        this.idTipoUnidadmedida = idTipoUnidadmedida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(Set tbProductos) {
        this.tbProductos = tbProductos;
    }




}


