package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoclasificacion generated by hbm2java
 */
public class TbTipoclasificacion  implements java.io.Serializable {


     private String idTipoClasificacion;
     private String nombre;
     private String descripcion;
     private Set tbProductos = new HashSet(0);

    public TbTipoclasificacion() {
    }

	
    public TbTipoclasificacion(String idTipoClasificacion, String nombre, String descripcion) {
        this.idTipoClasificacion = idTipoClasificacion;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TbTipoclasificacion(String idTipoClasificacion, String nombre, String descripcion, Set tbProductos) {
       this.idTipoClasificacion = idTipoClasificacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tbProductos = tbProductos;
    }
   
    public String getIdTipoClasificacion() {
        return this.idTipoClasificacion;
    }
    
    public void setIdTipoClasificacion(String idTipoClasificacion) {
        this.idTipoClasificacion = idTipoClasificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(Set tbProductos) {
        this.tbProductos = tbProductos;
    }




}


