package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipotasaiva generated by hbm2java
 */
public class TbTipotasaiva  implements java.io.Serializable {


     private String idTipoTasa;
     private String nombre;
     private float valor;
     private String descripcion;
     private Set tbProductos = new HashSet(0);

    public TbTipotasaiva() {
    }

	
    public TbTipotasaiva(String idTipoTasa, String nombre, float valor, String descripcion) {
        this.idTipoTasa = idTipoTasa;
        this.nombre = nombre;
        this.valor = valor;
        this.descripcion = descripcion;
    }
    public TbTipotasaiva(String idTipoTasa, String nombre, float valor, String descripcion, Set tbProductos) {
       this.idTipoTasa = idTipoTasa;
       this.nombre = nombre;
       this.valor = valor;
       this.descripcion = descripcion;
       this.tbProductos = tbProductos;
    }
   
    public String getIdTipoTasa() {
        return this.idTipoTasa;
    }
    
    public void setIdTipoTasa(String idTipoTasa) {
        this.idTipoTasa = idTipoTasa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(Set tbProductos) {
        this.tbProductos = tbProductos;
    }




}


