package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipopedido generated by hbm2java
 */
public class TbTipopedido  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set tbPedidoses = new HashSet(0);

    public TbTipopedido() {
    }

	
    public TbTipopedido(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public TbTipopedido(String nombre, String descripcion, Set tbPedidoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tbPedidoses = tbPedidoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbPedidoses() {
        return this.tbPedidoses;
    }
    
    public void setTbPedidoses(Set tbPedidoses) {
        this.tbPedidoses = tbPedidoses;
    }




}


