package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoUsuario generated by hbm2java
 */
public class TbTipoUsuario  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set tbUsuarioses = new HashSet(0);

    public TbTipoUsuario() {
    }

	
    public TbTipoUsuario(String descripcion) {
        this.descripcion = descripcion;
    }
    public TbTipoUsuario(String descripcion, Set tbUsuarioses) {
       this.descripcion = descripcion;
       this.tbUsuarioses = tbUsuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTbUsuarioses() {
        return this.tbUsuarioses;
    }
    
    public void setTbUsuarioses(Set tbUsuarioses) {
        this.tbUsuarioses = tbUsuarioses;
    }




}


