package Pojo;
// Generated 17-sep-2016 17:20:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipousuario generated by hbm2java
 */
public class TbTipousuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set tbUsuarioses = new HashSet(0);

    public TbTipousuario() {
    }

	
    public TbTipousuario(String nombre) {
        this.nombre = nombre;
    }
    public TbTipousuario(String nombre, Set tbUsuarioses) {
       this.nombre = nombre;
       this.tbUsuarioses = tbUsuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTbUsuarioses() {
        return this.tbUsuarioses;
    }
    
    public void setTbUsuarioses(Set tbUsuarioses) {
        this.tbUsuarioses = tbUsuarioses;
    }




}


