package Pojo;
// Generated 04-ago-2016 23:19:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUsuarios generated by hbm2java
 */
public class TbUsuarios  implements java.io.Serializable {


     private String cedula;
     private TbEmpresa tbEmpresa;
     private TbParroquia tbParroquia;
     private TbTipoUsuario tbTipoUsuario;
     private String nombres;
     private String apellidos;
     private String sexo;
     private String telefono;
     private String estadoCivil;
     private String direccion;
     private Date fechanacimiento;
     private String email;
     private String login;
     private String pass;
     private Character estado;
     private Set tbFacturas = new HashSet(0);
     private Set tbPedidoses = new HashSet(0);
     private Set tbDetallePermisos = new HashSet(0);

    public TbUsuarios() {
    }

	
    public TbUsuarios(String cedula, TbEmpresa tbEmpresa, TbParroquia tbParroquia, TbTipoUsuario tbTipoUsuario) {
        this.cedula = cedula;
        this.tbEmpresa = tbEmpresa;
        this.tbParroquia = tbParroquia;
        this.tbTipoUsuario = tbTipoUsuario;
    }
    public TbUsuarios(String cedula, TbEmpresa tbEmpresa, TbParroquia tbParroquia, TbTipoUsuario tbTipoUsuario, String nombres, String apellidos, String sexo, String telefono, String estadoCivil, String direccion, Date fechanacimiento, String email, String login, String pass, Character estado, Set tbFacturas, Set tbPedidoses, Set tbDetallePermisos) {
       this.cedula = cedula;
       this.tbEmpresa = tbEmpresa;
       this.tbParroquia = tbParroquia;
       this.tbTipoUsuario = tbTipoUsuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.telefono = telefono;
       this.estadoCivil = estadoCivil;
       this.direccion = direccion;
       this.fechanacimiento = fechanacimiento;
       this.email = email;
       this.login = login;
       this.pass = pass;
       this.estado = estado;
       this.tbFacturas = tbFacturas;
       this.tbPedidoses = tbPedidoses;
       this.tbDetallePermisos = tbDetallePermisos;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public TbEmpresa getTbEmpresa() {
        return this.tbEmpresa;
    }
    
    public void setTbEmpresa(TbEmpresa tbEmpresa) {
        this.tbEmpresa = tbEmpresa;
    }
    public TbParroquia getTbParroquia() {
        return this.tbParroquia;
    }
    
    public void setTbParroquia(TbParroquia tbParroquia) {
        this.tbParroquia = tbParroquia;
    }
    public TbTipoUsuario getTbTipoUsuario() {
        return this.tbTipoUsuario;
    }
    
    public void setTbTipoUsuario(TbTipoUsuario tbTipoUsuario) {
        this.tbTipoUsuario = tbTipoUsuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getTbFacturas() {
        return this.tbFacturas;
    }
    
    public void setTbFacturas(Set tbFacturas) {
        this.tbFacturas = tbFacturas;
    }
    public Set getTbPedidoses() {
        return this.tbPedidoses;
    }
    
    public void setTbPedidoses(Set tbPedidoses) {
        this.tbPedidoses = tbPedidoses;
    }
    public Set getTbDetallePermisos() {
        return this.tbDetallePermisos;
    }
    
    public void setTbDetallePermisos(Set tbDetallePermisos) {
        this.tbDetallePermisos = tbDetallePermisos;
    }




}


